apiVersion: apps/v1
kind: Deployment
metadata:
  name: dutcher-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dutcher-api
  template:
    metadata:
      labels:
        app: dutcher-api
    spec:
      imagePullSecrets:
      - name: github-registry-secret
      containers:
      - name: dutcher-api
        image: ghcr.io/jbloxsome/dutcher-api:SHA
        ports:
        - containerPort: 80
        env:
        - name: ODDSJAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: oddsjam
              key: api_key
        resources:
          requests:
            memory: 1024Mi
            cpu: 500m
          limits:
            memory: 2048Mi
            cpu: 1000m