services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
    - 8000:80
    volumes:
    - ./backend:/app
    environment:
      - THE_ODDS_API_KEY=${THE_ODDS_API_KEY}
  frontend:
    image: node:alpine
    ports:
    - 3000:3000
    volumes:
    - ./frontend:/app
    working_dir: /app
    command: >
      sh -c "yarn && yarn start:dev"