apiVersion: apps/v1
kind: Deployment
metadata:
  name: dutcher-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dutcher-frontend
  template:
    metadata:
      labels:
        app: dutcher-frontend
    spec:
      imagePullSecrets:
      - name: github-registry-secret
      containers:
      - name: dutcher-frontend
        image: ghcr.io/jbloxsome/dutcher-frontend:SHA
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 250m